### ISSUE TITLE
build failed on vue.js 2 when using lazy loading routes

### ISSUE THREAD

**Issue by harrisoff** [chrisvfritz/prerender-spa-plugin#277]
I used the [Vue.js 2 Router example](https://github.com/chrisvfritz/prerender-spa-plugin/tree/master/examples/vue2-webpack-router) given in README.md.
And I modified the routes as follows:
```ecmascript6
import Home from './Home.vue'
import Contact from './Contact.vue'
const router = new VueRouter({
  routes: [
    {path: '/', component: Home},
    {path: '/', component: Contact},
    // use lazy loading
    {path: '/about', component: () => import ('./components/About.vue')},
]})
```
The building progress would stop at `95% emitting` if there is a lazy-loading routes, even if this lazy-loading route will not be prerendered.

**Comment by Tribex** [comment]
What is your `PrerenderSPAPlugin` config?

**Comment by harrisoff** [comment]
> What is your `PrerenderSPAPlugin` config?

I did not modify `PrerenderSPAPlugin` configs.

I pushed my changes to my repo.

**Comment by Tribex** [comment]
@harrisoff The problem is here: https://github.com/harrisoff/prerender-spa-plugin/blob/master/examples/vue2-webpack-router/src/main.js#L44

```js
document.dispatchEvent(new Event('render-event'))
```

You need to wait to do this until after the lazy-loaded route loads.

**Comment by zydemail** [comment]
I use babel-plugin-syntax-dynamic-import in .babelrc, still have the same ,And I used the babel-plugin-syntax-dynamic-import as follows:
{
    "env": {
        "production": {
            "presets": [
                ["env", {
                    "targets": {
                        "browsers": ["last 2 version", "ie 10"]
                    },
                    "modules": false,
                    "debug": false
                }]
            ],
            "plugins": [
                "transform-runtime",
                "transform-object-rest-spread",
                "babel-plugin-syntax-dynamic-import",
                ["component", [
                    {
                    "libraryName": "mint-ui",
                    "style": true
                    }
                ]]
            ]
        },
        "development": {
            "presets": [
                ["env", {
                    "targets": {
                        "chrome": 60
                    },
                    "modules": false,
                    "debug": true
                }]
            ],
            "plugins": [
                "transform-object-rest-spread",
                "babel-plugin-syntax-dynamic-import",
                ["component", [
                    {
                    "libraryName": "mint-ui",
                    "style": true
                    }
                ]]
            ]
        }
    }
}
how to resolve the problem?

**Comment by zydemail** [comment]
I use babel-plugin-syntax-dynamic-import in .babelrc, still have the same ,And I used the babel-plugin-syntax-dynamic-import as follows:
```
{
    "env": {
        "production": {
            "presets": [
                ["env", {
                    "targets": {
                        "browsers": ["last 2 version", "ie 10"]
                    },
                    "modules": false,
                    "debug": false
                }]
            ],
            "plugins": [
                "transform-runtime",
                "transform-object-rest-spread",
                "babel-plugin-syntax-dynamic-import",
                ["component", [
                    {
                    "libraryName": "mint-ui",
                    "style": true
                    }
                ]]
            ]
        },
        "development": {
            "presets": [
                ["env", {
                    "targets": {
                        "chrome": 60
                    },
                    "modules": false,
                    "debug": true
                }]
            ],
            "plugins": [
                "transform-object-rest-spread",
                "babel-plugin-syntax-dynamic-import",
                ["component", [
                    {
                    "libraryName": "mint-ui",
                    "style": true
                    }
                ]]
            ]
        }
    }
}
```
how to resolve the problem?

**Comment by pallamollasai** [comment]
The following code worked for me. 

`const HomeComponent = () => System.import('../components/user/HomeComponent')
{
      name:"home",
      path:"/home",
      // HomeComponent
      component: HomeComponent
 }
`
